name: PHPStan

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  scan:

    runs-on: ubuntu-26.04 # ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: "ramsey/composer-install@4.0.0"

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run PHPStan
        run: php vendor/bin/phpstan analyse --error-format=github
