name: Run tests

on: [ push, pull_request ]

jobs:
  tests:

    runs-on: ubuntu-26.04 # ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: "ramsey/composer-install@v2"

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run DB
        run: |
          sudo docker run --rm -d \
            -e MYSQL_ROOT_PASSWORD=password \
            -e MYSQL_DATABASE=bookshelf \
            -e MYSQL_USER=app \
            -e "MYSQL_PASSWORD=!ChangeMe!" \
            -p 3306:3306 \
            "mariadb:10.11"

          sleep 60

      - name: Run test suite
        run: bin/phpunit
